### ISSUE TITLE
Topics for MDN Short Survey

### ISSUE THREAD

**Issue by dontcallmedom** [web-platform-dx/developer-research#8]
Assuming the opportunity for this group to propose short surveys to MDN is confirmed, what topics do we feel would benefit from this format for this potential broad exposure? Please submit one topic per comment (with some justification & context),. Please indicate support with :+1:  or lack thereof with :-1: reactions on the proposed topics.

**Comment by foolip** [comment]
I'd like to do a short survey asking developers to rank (somehow) proposals for Interop 2023. Using 2022 proposals as an example, we could ask developers to pick 3 features out of `@layer`, Subgrid, New Viewport Units, `<dialog>`, etc. The precise question type I'm not sure about, anything that results in a rough sorting would be OK.

We probably shouldn't reference Interop 2023, but ask more generally about which features developers are most keen to see broadly available and interoperable.

**Comment by tomayac** [comment]
This is somewhat vague, but on the Project Fugu 🐡 team we would like to get a better understanding to what extent developers would…
- use progressive enhancement and make use of a not universally supported feature on supporting browsers (progressive enhancement approach).
- not use a not universally supported feature to begin with (lowest common denominator approach).

I wrote "vague" because some features are…
- not replaceable but essential (think: [Web Bluetooth](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API)).
- not replaceable but not essential (think [Window Controls Overlay](https://web.dev/window-controls-overlay/)).
- somewhat replaceable but with slightly different behavior (think [`showSaveFilePicker()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker) _vs._ `<a download>`).

**Comment by ststimac** [comment]
This feels like a good spot where we could link to the Web We Want but perhaps we could list 5-10 of the most upvoted Wants w/links to the discussion pages and have developers pick their top 3 out of the list.

**Comment by captainbrosset** [comment]
I, like @foolip, would ask developers to share what they are most interested in getting more broadly implemented in browsers.

**Comment by una** [comment]
Can we also address the top pain points from the last survey(s) and see if they are still top pain points or things have gotten better? I think this mapping over time is valuable:

<img width="1023" alt="Screen Shot 2022-08-12 at 11 33 30 AM" src="https://user-images.githubusercontent.com/1693164/184389460-3c5b08f4-3833-4e5e-bd2b-3527cdffd4a2.png">

**Comment by atopal** [comment]
Maybe a repeat of the developers satisfaction question from previous MDN Web DNAs to see if it has changed one way or the other?
-  "How would you rate your overall satisfaction with the Web, as a platform and set of tools, to enable you to build what you need or want?

**Comment by atopal** [comment]
A question to better understand which browsers developers consider when they decide whether to use a feature or not? Find out whether there is a core browser set or whether it's multiple browser sets (eg desktop websites vs mobile websites, or based on geography, etc.)

**Comment by dontcallmedom** [comment]
Discussion on this will happen as part of the MDN repo, so closing this issue
